<?php

$collection = $this->getPostCollection();
?>
<table class="data table" id="membership">
    <caption class="table-caption">Vky Test Data</caption>
    <thead>
    <tr>
        <th scope="col" class="col membership_id">ID #</th>
        <th scope="col" class="col name">Name</th>
        <th scope="col" class="col description">Description</th>
        <th scope="col" class="col discount">Discount</th>
        <th scope="col" class="col discount_type">Discount Type</th>
        <th scope="col" class="col status">Status</th>
        <th scope="col" class="col actions">Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($collection as $key => $index): ?>
        <tr>
            <td data-th="ID #" class="col membership_id"><?php echo $index->getMembershipId(); ?></td>
            <td data-th="Name" class="col name"><?php echo $index->getName(); ?></td>
            <td data-th="Description" class="col description"><?php echo $index->getDescription(); ?></td>
            <td data-th="Discount" class="col discount"><?php echo $index->getdDiscountt(); ?></td>
            <td data-th="Discount Type" class="col discount_type"><?php echo $index->getDiscountType(); ?></td>
            <td data-th="Status" class="col status"><?php echo $index->getStatus(); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
