<?php
/**
 * var $block \Eagle\Membership\Membership\Index
 * var $collection Eagle\Membership\Membership\Index
 */
?>
<?php
    $collection = $this->getPostCollection();
?>
<table class="data table" id="membership">
    <caption class="table-caption">Membership</caption>
    <thead>
    <tr>
        <th scope="col" class="col membership_id">ID #</th>
        <th scope="col" class="col name">Name</th>
        <th scope="col" class="col description">Description</th>
        <th scope="col" class="col discount">Discount</th>
        <th scope="col" class="col discount_type">Discount Type</th>
        <th scope="col" class="col status">Status</th>
        <th scope="col" class="col actions">Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($collection as $key => $index): ?>
        <tr>
            <td data-th="ID #" class="col membership_id"><?php echo $index->getMembershipId(); ?></td>
            <td data-th="Name" class="col name"><?php echo $index->getName(); ?></td>
            <td data-th="Description" class="col description"><?php echo $index->getDescription(); ?></td>
            <td data-th="Discount" class="col discount"><?php echo $index->getDiscount(); ?></td>
            <td data-th="Discount Type" class="col discount_type"><?php if ($index->getDiscountType() == 1) {
                    echo "Fixed";
                } else {
                    echo "Percent";
                }; ?></td>
            <td data-th="Status"
                class="col status"><?php if ($index->getStatus()) echo "Enabled"; else echo "Disabled"; ?></td>
            <td data-th="Actions" class="col actions">
                <a href="<?= $block->getUrl('membership/index/view', ['id' => $index->getMembershipId()]) ?>" class="actions view">
                    <span><?php  echo __('View') ?></span>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
