<?php

$singleData = $this->getSingleData();
?>
<div>
    <h3>Name</h3>
    <p><?php echo $singleData->getName(); ?></p>
</div>
<div>
    <h3>Description</h3>
    <p><?php echo $singleData->getDescription(); ?></p>
</div>
<div>
    <h3>Discount</h3>
    <p><?php echo $singleData->getDiscount(); ?></p>
</div>
<div>
    <h3>Discount Type</h3>
    <p><?php if ($singleData->getDiscountType() == 1) {
            echo "Fixed";
        } else {
            echo "Percent";
        }; ?></p>
</div>
<div>
    <h3>Status</h3>
    <p><?php if ($singleData->getStatus()) echo "Enabled"; else echo "Disabled"; ?></p>
</div>
